[package]
name = "nsgn"
version = "0.1.0"
authors = ["npes-95 <npe.smith.95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
hound = "3.4.0"
rand = "0.7"