[package]
name = "nsgn"
version = "0.1.0"
authors = ["npes-95 <npe.smith.95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
hound = "3.4.0"
rand = "0.7"